app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# In order to use the built-in email functionality (confirmation of the account, resetting of the password), you must
# activate and configure the SwiftmailerBundle.
# https://symfony.com/doc/master/bundles/FOSUserBundle/index.html
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
